import os
import streamlit as st
from dotenv import load_dotenv

# Load environment variables (.env file)
load_dotenv()

# Import your crew class
from agentic_rag_example.crew import AgenticRagExample

# Page Config
st.set_page_config(
    page_title="Netflix Movie Recommender",
    page_icon="🎬",
    layout="centered"
)

# App UI Header
st.title("🎬 Agentic Netflix Recommender")
st.caption("Powered by CrewAI (RAG Agent, Exa Search Agent, Report Agent) & Weaviate")

st.markdown("---")

# Verify essential API Keys are present
required_keys = ["OPENAI_API_KEY", "WEAVIATE_URL", "WEAVIATE_API_KEY", "EXA_API_KEY"]
missing_keys = [key for key in required_keys if not os.environ.get(key)]

if missing_keys:
    st.error(f"Missing environment variables: `{', '.join(missing_keys)}`. Please configure them in your `.env` file.")

# Input form for the user
with st.form("recommendation_form"):
    user_query = st.text_area(
        "What kind of movie or TV show are you in the mood for?",
        placeholder="E.g., I want a dark sci-fi thriller with plot twists similar to Black Mirror or Inception.",
        height=100
    )
    
    # Add any extra dynamic inputs expected by your tasks.yaml here
    additional_context = st.text_input(
        "Any preferred genres, actors, or constraints? (Optional)",
        placeholder="E.g., Released after 2015, Mind-bending, Action"
    )

    submit_button = st.form_submit_button("🔍 Search & Generate Recommendations")

# Execution flow
if submit_button:
    if not user_query.strip():
        st.warning("Please describe what kind of movie or recommendations you are looking for.")
    else:
        with st.status("🤖 Agents at work...", expanded=True) as status:
            st.write("🔎 **RAG Agent:** Querying Weaviate Vector DB (`netflix_data_system_full`)...")
            st.write("🌐 **Expand Details Agent:** Fetching real-time metadata via Exa Search Tool...")
            st.write("📝 **Report Agent:** Synthesizing findings into your final recommendation report...")

            try:
                # 1. Map inputs to the placeholders expected by your tasks.yaml
                # Ensure the key names match the `{variable_name}` variables in your tasks.yaml
                inputs = {
                    "query": user_query,
                    "topic": user_query,  # Common placeholder fallback in CrewAI templates
                    "context": additional_context
                }

                # 2. Instantiate and kickoff your crew
                crew_instance = AgenticRagExample().crew()
                result = crew_instance.kickoff(inputs=inputs)

                status.update(label="✅ Recommendations generated successfully!", state="complete", expanded=False)

                # Display Results
                st.subheader("🍿 Your Recommended Movies")
                
                # Render raw markdown response from Crew output
                st.markdown(result.raw)

                # Optional: Read back from report.md generated by expand_details_task / report_task
                if os.path.exists("report.md"):
                    with open("report.md", "r") as f:
                        report_content = f.read()
                    
                    st.download_button(
                        label="📥 Download Report (.md)",
                        data=report_content,
                        file_name="netflix_recommendations.md",
                        mime="text/markdown"
                    )

            except Exception as e:
                status.update(label="❌ Failed to execute agent pipeline", state="error", expanded=True)
                st.error(f"An error occurred while executing the Crew: {e}")